import Head from 'next/head'

import homeStyles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Leapfrog Technology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={homeStyles.hero}>
        <div className={homeStyles.herocontent}>
        <h1>
          Innovate Better, <br/>
        <span>faster.</span>
        </h1>
        <p>
        We help businesses imagine and create the digital experiences of tomorrow. We succeed together by blending the best of entrepreneurship, startup thinking, and world-class engineering.
        </p>
        </div>
        <div  className={homeStyles.herodowncontent}>
        <section className={homeStyles.getstartedbtn}>
        <button> Get Started <span>A</span> </button>
        </section>
        <section className={homeStyles.learnmoresection}>
        <p>Want to know how we stand out <br/>
        <span> Learn More</span>
        </p>
        </section>
        </div>
        </div>
        <div className={homeStyles.ceosection}>
          <p className={homeStyles.quote} >
          “It would have taken months to build the product team that we inherited overnight with Leapfrog. They're built for startup speed, and they have consistently delivered a well-engineered product for us. Laudio is my second partnership with Leapfrog, and they have earned my trust.”
          </p>
          <img src='https://www.lftechnology.com/wp-content/themes/Froggy/dist/images/testimonial_person.png' 
          height={60} width={60}/>
         <p className={homeStyles.ceoname} >
          Russ Richmond, MD <br/>
          <span> CEO, Laudio, Boston</span>
          </p>
          <img src='https://www.lftechnology.com/wp-content/themes/Froggy/dist/images/testimonial_laudio.png' 
          height={72} width={101}/>
        </div>
        <div className={homeStyles.caraouselsection}>
          <div>
          <h1>
          We help ambitious clients achieve extraordinary outcomes
          </h1>
          </div>
        </div>
        <div className={homeStyles.showmenowsection}>
          <div className={homeStyles.showmesection_top}>
            <div className={homeStyles.showmesection_title}>
            <h1>
            Design, build and scale your vision
            </h1>
            <button>show me now <span>A</span></button>
            </div>
            <div className={homeStyles.showme_subtitle}>
            <p>
            We're ready to be your secret digital weapon. And we're flexible. Work with just our developers or designers, or partner with us along your entire digital journey.
            </p>
            </div>

          </div>
          <div className={homeStyles.number_coloumn}>
            <div>
              <button>1</button>
              <h1>Investigate</h1>
              <p>Discovery Workshops
              Process Mapping
              Learn Canvas
              Market Research
              Goal Setting
              </p>              
            </div>
            <div> 
            <button>2</button>
            <h1>Design</h1>
              </div>
            <div> 
            <button>3</button>
            <h1>Develop</h1>
              </div>
            <div>
            <button>4</button>
            <h1>Lunch</h1>
               </div>
            <div>
            <button>5</button>
            <h1>Scale</h1>
            </div>
            
          </div>

        </div>
      <footer>
      </footer>
    </div>
  )
}
